# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sudoku_solver.ui'
#
# Created: Sun Nov 26 20:12:37 2017
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(611, 668)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(-1, -1, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_3.addWidget(self.label)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setMargin(20)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.cell79 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell79.sizePolicy().hasHeightForWidth())
        self.cell79.setSizePolicy(sizePolicy)
        self.cell79.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell79.setFont(font)
        self.cell79.setMaxLength(1)
        self.cell79.setAlignment(QtCore.Qt.AlignCenter)
        self.cell79.setObjectName(_fromUtf8("cell79"))
        self.gridLayout_3.addWidget(self.cell79, 10, 8, 1, 1)
        self.line_4 = QtGui.QFrame(self.centralwidget)
        self.line_4.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_3.addWidget(self.line_4, 4, 7, 3, 1)
        self.cell62 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell62.sizePolicy().hasHeightForWidth())
        self.cell62.setSizePolicy(sizePolicy)
        self.cell62.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell62.setFont(font)
        self.cell62.setMaxLength(1)
        self.cell62.setAlignment(QtCore.Qt.AlignCenter)
        self.cell62.setObjectName(_fromUtf8("cell62"))
        self.gridLayout_3.addWidget(self.cell62, 8, 9, 1, 1)
        self.cell63 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell63.sizePolicy().hasHeightForWidth())
        self.cell63.setSizePolicy(sizePolicy)
        self.cell63.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell63.setFont(font)
        self.cell63.setMaxLength(1)
        self.cell63.setAlignment(QtCore.Qt.AlignCenter)
        self.cell63.setObjectName(_fromUtf8("cell63"))
        self.gridLayout_3.addWidget(self.cell63, 8, 10, 1, 1)
        self.cell76 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell76.sizePolicy().hasHeightForWidth())
        self.cell76.setSizePolicy(sizePolicy)
        self.cell76.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell76.setFont(font)
        self.cell76.setMaxLength(1)
        self.cell76.setAlignment(QtCore.Qt.AlignCenter)
        self.cell76.setObjectName(_fromUtf8("cell76"))
        self.gridLayout_3.addWidget(self.cell76, 10, 4, 1, 1)
        self.cell38 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell38.sizePolicy().hasHeightForWidth())
        self.cell38.setSizePolicy(sizePolicy)
        self.cell38.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell38.setFont(font)
        self.cell38.setMaxLength(1)
        self.cell38.setAlignment(QtCore.Qt.AlignCenter)
        self.cell38.setObjectName(_fromUtf8("cell38"))
        self.gridLayout_3.addWidget(self.cell38, 5, 1, 1, 1)
        self.cell72 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell72.sizePolicy().hasHeightForWidth())
        self.cell72.setSizePolicy(sizePolicy)
        self.cell72.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell72.setFont(font)
        self.cell72.setMaxLength(1)
        self.cell72.setAlignment(QtCore.Qt.AlignCenter)
        self.cell72.setObjectName(_fromUtf8("cell72"))
        self.gridLayout_3.addWidget(self.cell72, 9, 10, 1, 1)
        self.cell60 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell60.sizePolicy().hasHeightForWidth())
        self.cell60.setSizePolicy(sizePolicy)
        self.cell60.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell60.setFont(font)
        self.cell60.setMaxLength(1)
        self.cell60.setAlignment(QtCore.Qt.AlignCenter)
        self.cell60.setObjectName(_fromUtf8("cell60"))
        self.gridLayout_3.addWidget(self.cell60, 8, 6, 1, 1)
        self.cell59 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell59.sizePolicy().hasHeightForWidth())
        self.cell59.setSizePolicy(sizePolicy)
        self.cell59.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell59.setFont(font)
        self.cell59.setMaxLength(1)
        self.cell59.setAlignment(QtCore.Qt.AlignCenter)
        self.cell59.setObjectName(_fromUtf8("cell59"))
        self.gridLayout_3.addWidget(self.cell59, 8, 5, 1, 1)
        self.cell22 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell22.sizePolicy().hasHeightForWidth())
        self.cell22.setSizePolicy(sizePolicy)
        self.cell22.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell22.setFont(font)
        self.cell22.setMaxLength(1)
        self.cell22.setAlignment(QtCore.Qt.AlignCenter)
        self.cell22.setObjectName(_fromUtf8("cell22"))
        self.gridLayout_3.addWidget(self.cell22, 2, 4, 1, 1)
        self.line = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMinimumSize(QtCore.QSize(0, 10))
        self.line.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.line.setFont(font)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_3.addWidget(self.line, 7, 0, 1, 11)
        self.cell75 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell75.sizePolicy().hasHeightForWidth())
        self.cell75.setSizePolicy(sizePolicy)
        self.cell75.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell75.setFont(font)
        self.cell75.setMaxLength(1)
        self.cell75.setAlignment(QtCore.Qt.AlignCenter)
        self.cell75.setObjectName(_fromUtf8("cell75"))
        self.gridLayout_3.addWidget(self.cell75, 10, 2, 1, 1)
        self.cell44 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell44.sizePolicy().hasHeightForWidth())
        self.cell44.setSizePolicy(sizePolicy)
        self.cell44.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell44.setFont(font)
        self.cell44.setMaxLength(1)
        self.cell44.setAlignment(QtCore.Qt.AlignCenter)
        self.cell44.setObjectName(_fromUtf8("cell44"))
        self.gridLayout_3.addWidget(self.cell44, 5, 9, 1, 1)
        self.line_3 = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_3.addWidget(self.line_3, 4, 3, 3, 1)
        self.cell28 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell28.sizePolicy().hasHeightForWidth())
        self.cell28.setSizePolicy(sizePolicy)
        self.cell28.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell28.setFont(font)
        self.cell28.setMaxLength(1)
        self.cell28.setAlignment(QtCore.Qt.AlignCenter)
        self.cell28.setObjectName(_fromUtf8("cell28"))
        self.gridLayout_3.addWidget(self.cell28, 4, 0, 1, 1)
        self.cell23 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell23.sizePolicy().hasHeightForWidth())
        self.cell23.setSizePolicy(sizePolicy)
        self.cell23.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell23.setFont(font)
        self.cell23.setMaxLength(1)
        self.cell23.setAlignment(QtCore.Qt.AlignCenter)
        self.cell23.setObjectName(_fromUtf8("cell23"))
        self.gridLayout_3.addWidget(self.cell23, 2, 5, 1, 1)
        self.cell24 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell24.sizePolicy().hasHeightForWidth())
        self.cell24.setSizePolicy(sizePolicy)
        self.cell24.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell24.setFont(font)
        self.cell24.setMaxLength(1)
        self.cell24.setAlignment(QtCore.Qt.AlignCenter)
        self.cell24.setObjectName(_fromUtf8("cell24"))
        self.gridLayout_3.addWidget(self.cell24, 2, 6, 1, 1)
        self.cell8 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell8.sizePolicy().hasHeightForWidth())
        self.cell8.setSizePolicy(sizePolicy)
        self.cell8.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell8.setFont(font)
        self.cell8.setMaxLength(1)
        self.cell8.setAlignment(QtCore.Qt.AlignCenter)
        self.cell8.setObjectName(_fromUtf8("cell8"))
        self.gridLayout_3.addWidget(self.cell8, 0, 9, 1, 1)
        self.cell45 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell45.sizePolicy().hasHeightForWidth())
        self.cell45.setSizePolicy(sizePolicy)
        self.cell45.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell45.setFont(font)
        self.cell45.setMaxLength(1)
        self.cell45.setAlignment(QtCore.Qt.AlignCenter)
        self.cell45.setObjectName(_fromUtf8("cell45"))
        self.gridLayout_3.addWidget(self.cell45, 5, 10, 1, 1)
        self.cell66 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell66.sizePolicy().hasHeightForWidth())
        self.cell66.setSizePolicy(sizePolicy)
        self.cell66.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell66.setFont(font)
        self.cell66.setMaxLength(1)
        self.cell66.setAlignment(QtCore.Qt.AlignCenter)
        self.cell66.setObjectName(_fromUtf8("cell66"))
        self.gridLayout_3.addWidget(self.cell66, 9, 2, 1, 1)
        self.cell1 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell1.sizePolicy().hasHeightForWidth())
        self.cell1.setSizePolicy(sizePolicy)
        self.cell1.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell1.setFont(font)
        self.cell1.setMaxLength(1)
        self.cell1.setAlignment(QtCore.Qt.AlignCenter)
        self.cell1.setObjectName(_fromUtf8("cell1"))
        self.gridLayout_3.addWidget(self.cell1, 0, 0, 1, 1)
        self.cell55 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell55.sizePolicy().hasHeightForWidth())
        self.cell55.setSizePolicy(sizePolicy)
        self.cell55.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell55.setFont(font)
        self.cell55.setMaxLength(1)
        self.cell55.setAlignment(QtCore.Qt.AlignCenter)
        self.cell55.setObjectName(_fromUtf8("cell55"))
        self.gridLayout_3.addWidget(self.cell55, 8, 0, 1, 1)
        self.cell17 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell17.sizePolicy().hasHeightForWidth())
        self.cell17.setSizePolicy(sizePolicy)
        self.cell17.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell17.setFont(font)
        self.cell17.setMaxLength(1)
        self.cell17.setAlignment(QtCore.Qt.AlignCenter)
        self.cell17.setObjectName(_fromUtf8("cell17"))
        self.gridLayout_3.addWidget(self.cell17, 1, 9, 1, 1)
        self.cell26 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell26.sizePolicy().hasHeightForWidth())
        self.cell26.setSizePolicy(sizePolicy)
        self.cell26.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell26.setFont(font)
        self.cell26.setMaxLength(1)
        self.cell26.setAlignment(QtCore.Qt.AlignCenter)
        self.cell26.setObjectName(_fromUtf8("cell26"))
        self.gridLayout_3.addWidget(self.cell26, 2, 9, 1, 1)
        self.cell64 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell64.sizePolicy().hasHeightForWidth())
        self.cell64.setSizePolicy(sizePolicy)
        self.cell64.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell64.setFont(font)
        self.cell64.setMaxLength(1)
        self.cell64.setAlignment(QtCore.Qt.AlignCenter)
        self.cell64.setObjectName(_fromUtf8("cell64"))
        self.gridLayout_3.addWidget(self.cell64, 9, 0, 1, 1)
        self.cell31 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell31.sizePolicy().hasHeightForWidth())
        self.cell31.setSizePolicy(sizePolicy)
        self.cell31.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell31.setFont(font)
        self.cell31.setMaxLength(1)
        self.cell31.setAlignment(QtCore.Qt.AlignCenter)
        self.cell31.setObjectName(_fromUtf8("cell31"))
        self.gridLayout_3.addWidget(self.cell31, 4, 4, 1, 1)
        self.cell48 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell48.sizePolicy().hasHeightForWidth())
        self.cell48.setSizePolicy(sizePolicy)
        self.cell48.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell48.setFont(font)
        self.cell48.setMaxLength(1)
        self.cell48.setAlignment(QtCore.Qt.AlignCenter)
        self.cell48.setObjectName(_fromUtf8("cell48"))
        self.gridLayout_3.addWidget(self.cell48, 6, 2, 1, 1)
        self.cell81 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell81.sizePolicy().hasHeightForWidth())
        self.cell81.setSizePolicy(sizePolicy)
        self.cell81.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell81.setFont(font)
        self.cell81.setMaxLength(1)
        self.cell81.setAlignment(QtCore.Qt.AlignCenter)
        self.cell81.setObjectName(_fromUtf8("cell81"))
        self.gridLayout_3.addWidget(self.cell81, 10, 10, 1, 1)
        self.cell13 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell13.sizePolicy().hasHeightForWidth())
        self.cell13.setSizePolicy(sizePolicy)
        self.cell13.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell13.setFont(font)
        self.cell13.setMaxLength(1)
        self.cell13.setAlignment(QtCore.Qt.AlignCenter)
        self.cell13.setObjectName(_fromUtf8("cell13"))
        self.gridLayout_3.addWidget(self.cell13, 1, 4, 1, 1)
        self.cell68 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell68.sizePolicy().hasHeightForWidth())
        self.cell68.setSizePolicy(sizePolicy)
        self.cell68.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell68.setFont(font)
        self.cell68.setMaxLength(1)
        self.cell68.setAlignment(QtCore.Qt.AlignCenter)
        self.cell68.setObjectName(_fromUtf8("cell68"))
        self.gridLayout_3.addWidget(self.cell68, 9, 5, 1, 1)
        self.cell77 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell77.sizePolicy().hasHeightForWidth())
        self.cell77.setSizePolicy(sizePolicy)
        self.cell77.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell77.setFont(font)
        self.cell77.setMaxLength(1)
        self.cell77.setAlignment(QtCore.Qt.AlignCenter)
        self.cell77.setObjectName(_fromUtf8("cell77"))
        self.gridLayout_3.addWidget(self.cell77, 10, 5, 1, 1)
        self.cell78 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell78.sizePolicy().hasHeightForWidth())
        self.cell78.setSizePolicy(sizePolicy)
        self.cell78.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell78.setFont(font)
        self.cell78.setMaxLength(1)
        self.cell78.setAlignment(QtCore.Qt.AlignCenter)
        self.cell78.setObjectName(_fromUtf8("cell78"))
        self.gridLayout_3.addWidget(self.cell78, 10, 6, 1, 1)
        self.cell61 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell61.sizePolicy().hasHeightForWidth())
        self.cell61.setSizePolicy(sizePolicy)
        self.cell61.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell61.setFont(font)
        self.cell61.setMaxLength(1)
        self.cell61.setAlignment(QtCore.Qt.AlignCenter)
        self.cell61.setObjectName(_fromUtf8("cell61"))
        self.gridLayout_3.addWidget(self.cell61, 8, 8, 1, 1)
        self.cell69 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell69.sizePolicy().hasHeightForWidth())
        self.cell69.setSizePolicy(sizePolicy)
        self.cell69.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell69.setFont(font)
        self.cell69.setMaxLength(1)
        self.cell69.setAlignment(QtCore.Qt.AlignCenter)
        self.cell69.setObjectName(_fromUtf8("cell69"))
        self.gridLayout_3.addWidget(self.cell69, 9, 6, 1, 1)
        self.cell7 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell7.sizePolicy().hasHeightForWidth())
        self.cell7.setSizePolicy(sizePolicy)
        self.cell7.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell7.setFont(font)
        self.cell7.setMaxLength(1)
        self.cell7.setAlignment(QtCore.Qt.AlignCenter)
        self.cell7.setObjectName(_fromUtf8("cell7"))
        self.gridLayout_3.addWidget(self.cell7, 0, 8, 1, 1)
        self.cell58 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell58.sizePolicy().hasHeightForWidth())
        self.cell58.setSizePolicy(sizePolicy)
        self.cell58.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell58.setFont(font)
        self.cell58.setMaxLength(1)
        self.cell58.setAlignment(QtCore.Qt.AlignCenter)
        self.cell58.setObjectName(_fromUtf8("cell58"))
        self.gridLayout_3.addWidget(self.cell58, 8, 4, 1, 1)
        self.cell20 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell20.sizePolicy().hasHeightForWidth())
        self.cell20.setSizePolicy(sizePolicy)
        self.cell20.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell20.setFont(font)
        self.cell20.setMaxLength(1)
        self.cell20.setAlignment(QtCore.Qt.AlignCenter)
        self.cell20.setObjectName(_fromUtf8("cell20"))
        self.gridLayout_3.addWidget(self.cell20, 2, 1, 1, 1)
        self.cell16 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell16.sizePolicy().hasHeightForWidth())
        self.cell16.setSizePolicy(sizePolicy)
        self.cell16.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell16.setFont(font)
        self.cell16.setMaxLength(1)
        self.cell16.setAlignment(QtCore.Qt.AlignCenter)
        self.cell16.setObjectName(_fromUtf8("cell16"))
        self.gridLayout_3.addWidget(self.cell16, 1, 8, 1, 1)
        self.cell9 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell9.sizePolicy().hasHeightForWidth())
        self.cell9.setSizePolicy(sizePolicy)
        self.cell9.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell9.setFont(font)
        self.cell9.setMaxLength(1)
        self.cell9.setAlignment(QtCore.Qt.AlignCenter)
        self.cell9.setObjectName(_fromUtf8("cell9"))
        self.gridLayout_3.addWidget(self.cell9, 0, 10, 1, 1)
        self.cell70 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell70.sizePolicy().hasHeightForWidth())
        self.cell70.setSizePolicy(sizePolicy)
        self.cell70.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell70.setFont(font)
        self.cell70.setMaxLength(1)
        self.cell70.setAlignment(QtCore.Qt.AlignCenter)
        self.cell70.setObjectName(_fromUtf8("cell70"))
        self.gridLayout_3.addWidget(self.cell70, 9, 8, 1, 1)
        self.cell47 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell47.sizePolicy().hasHeightForWidth())
        self.cell47.setSizePolicy(sizePolicy)
        self.cell47.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell47.setFont(font)
        self.cell47.setMaxLength(1)
        self.cell47.setAlignment(QtCore.Qt.AlignCenter)
        self.cell47.setObjectName(_fromUtf8("cell47"))
        self.gridLayout_3.addWidget(self.cell47, 6, 1, 1, 1)
        self.cell74 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell74.sizePolicy().hasHeightForWidth())
        self.cell74.setSizePolicy(sizePolicy)
        self.cell74.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell74.setFont(font)
        self.cell74.setMaxLength(1)
        self.cell74.setAlignment(QtCore.Qt.AlignCenter)
        self.cell74.setObjectName(_fromUtf8("cell74"))
        self.gridLayout_3.addWidget(self.cell74, 10, 1, 1, 1)
        self.cell54 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell54.sizePolicy().hasHeightForWidth())
        self.cell54.setSizePolicy(sizePolicy)
        self.cell54.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell54.setFont(font)
        self.cell54.setMaxLength(1)
        self.cell54.setAlignment(QtCore.Qt.AlignCenter)
        self.cell54.setObjectName(_fromUtf8("cell54"))
        self.gridLayout_3.addWidget(self.cell54, 6, 10, 1, 1)
        self.cell15 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell15.sizePolicy().hasHeightForWidth())
        self.cell15.setSizePolicy(sizePolicy)
        self.cell15.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell15.setFont(font)
        self.cell15.setMaxLength(1)
        self.cell15.setAlignment(QtCore.Qt.AlignCenter)
        self.cell15.setObjectName(_fromUtf8("cell15"))
        self.gridLayout_3.addWidget(self.cell15, 1, 6, 1, 1)
        self.cell71 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell71.sizePolicy().hasHeightForWidth())
        self.cell71.setSizePolicy(sizePolicy)
        self.cell71.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell71.setFont(font)
        self.cell71.setMaxLength(1)
        self.cell71.setAlignment(QtCore.Qt.AlignCenter)
        self.cell71.setObjectName(_fromUtf8("cell71"))
        self.gridLayout_3.addWidget(self.cell71, 9, 9, 1, 1)
        self.cell73 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell73.sizePolicy().hasHeightForWidth())
        self.cell73.setSizePolicy(sizePolicy)
        self.cell73.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell73.setFont(font)
        self.cell73.setMaxLength(1)
        self.cell73.setAlignment(QtCore.Qt.AlignCenter)
        self.cell73.setObjectName(_fromUtf8("cell73"))
        self.gridLayout_3.addWidget(self.cell73, 10, 0, 1, 1)
        self.cell33 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell33.sizePolicy().hasHeightForWidth())
        self.cell33.setSizePolicy(sizePolicy)
        self.cell33.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell33.setFont(font)
        self.cell33.setMaxLength(1)
        self.cell33.setAlignment(QtCore.Qt.AlignCenter)
        self.cell33.setObjectName(_fromUtf8("cell33"))
        self.gridLayout_3.addWidget(self.cell33, 4, 6, 1, 1)
        self.cell51 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell51.sizePolicy().hasHeightForWidth())
        self.cell51.setSizePolicy(sizePolicy)
        self.cell51.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell51.setFont(font)
        self.cell51.setMaxLength(1)
        self.cell51.setAlignment(QtCore.Qt.AlignCenter)
        self.cell51.setObjectName(_fromUtf8("cell51"))
        self.gridLayout_3.addWidget(self.cell51, 6, 6, 1, 1)
        self.cell57 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell57.sizePolicy().hasHeightForWidth())
        self.cell57.setSizePolicy(sizePolicy)
        self.cell57.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell57.setFont(font)
        self.cell57.setMaxLength(1)
        self.cell57.setAlignment(QtCore.Qt.AlignCenter)
        self.cell57.setObjectName(_fromUtf8("cell57"))
        self.gridLayout_3.addWidget(self.cell57, 8, 2, 1, 1)
        self.cell67 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell67.sizePolicy().hasHeightForWidth())
        self.cell67.setSizePolicy(sizePolicy)
        self.cell67.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell67.setFont(font)
        self.cell67.setMaxLength(1)
        self.cell67.setAlignment(QtCore.Qt.AlignCenter)
        self.cell67.setObjectName(_fromUtf8("cell67"))
        self.gridLayout_3.addWidget(self.cell67, 9, 4, 1, 1)
        self.cell41 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell41.sizePolicy().hasHeightForWidth())
        self.cell41.setSizePolicy(sizePolicy)
        self.cell41.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell41.setFont(font)
        self.cell41.setMaxLength(1)
        self.cell41.setAlignment(QtCore.Qt.AlignCenter)
        self.cell41.setObjectName(_fromUtf8("cell41"))
        self.gridLayout_3.addWidget(self.cell41, 5, 5, 1, 1)
        self.cell42 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell42.sizePolicy().hasHeightForWidth())
        self.cell42.setSizePolicy(sizePolicy)
        self.cell42.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell42.setFont(font)
        self.cell42.setMaxLength(1)
        self.cell42.setAlignment(QtCore.Qt.AlignCenter)
        self.cell42.setObjectName(_fromUtf8("cell42"))
        self.gridLayout_3.addWidget(self.cell42, 5, 6, 1, 1)
        self.cell39 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell39.sizePolicy().hasHeightForWidth())
        self.cell39.setSizePolicy(sizePolicy)
        self.cell39.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell39.setFont(font)
        self.cell39.setMaxLength(1)
        self.cell39.setAlignment(QtCore.Qt.AlignCenter)
        self.cell39.setObjectName(_fromUtf8("cell39"))
        self.gridLayout_3.addWidget(self.cell39, 5, 2, 1, 1)
        self.cell46 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell46.sizePolicy().hasHeightForWidth())
        self.cell46.setSizePolicy(sizePolicy)
        self.cell46.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell46.setFont(font)
        self.cell46.setMaxLength(1)
        self.cell46.setAlignment(QtCore.Qt.AlignCenter)
        self.cell46.setObjectName(_fromUtf8("cell46"))
        self.gridLayout_3.addWidget(self.cell46, 6, 0, 1, 1)
        self.cell52 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell52.sizePolicy().hasHeightForWidth())
        self.cell52.setSizePolicy(sizePolicy)
        self.cell52.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell52.setFont(font)
        self.cell52.setMaxLength(1)
        self.cell52.setAlignment(QtCore.Qt.AlignCenter)
        self.cell52.setObjectName(_fromUtf8("cell52"))
        self.gridLayout_3.addWidget(self.cell52, 6, 8, 1, 1)
        self.cell32 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell32.sizePolicy().hasHeightForWidth())
        self.cell32.setSizePolicy(sizePolicy)
        self.cell32.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell32.setFont(font)
        self.cell32.setMaxLength(1)
        self.cell32.setAlignment(QtCore.Qt.AlignCenter)
        self.cell32.setObjectName(_fromUtf8("cell32"))
        self.gridLayout_3.addWidget(self.cell32, 4, 5, 1, 1)
        self.cell40 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell40.sizePolicy().hasHeightForWidth())
        self.cell40.setSizePolicy(sizePolicy)
        self.cell40.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell40.setFont(font)
        self.cell40.setMaxLength(1)
        self.cell40.setAlignment(QtCore.Qt.AlignCenter)
        self.cell40.setObjectName(_fromUtf8("cell40"))
        self.gridLayout_3.addWidget(self.cell40, 5, 4, 1, 1)
        self.cell30 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell30.sizePolicy().hasHeightForWidth())
        self.cell30.setSizePolicy(sizePolicy)
        self.cell30.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell30.setFont(font)
        self.cell30.setMaxLength(1)
        self.cell30.setAlignment(QtCore.Qt.AlignCenter)
        self.cell30.setObjectName(_fromUtf8("cell30"))
        self.gridLayout_3.addWidget(self.cell30, 4, 2, 1, 1)
        self.cell49 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell49.sizePolicy().hasHeightForWidth())
        self.cell49.setSizePolicy(sizePolicy)
        self.cell49.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell49.setFont(font)
        self.cell49.setMaxLength(1)
        self.cell49.setAlignment(QtCore.Qt.AlignCenter)
        self.cell49.setObjectName(_fromUtf8("cell49"))
        self.gridLayout_3.addWidget(self.cell49, 6, 4, 1, 1)
        self.cell50 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell50.sizePolicy().hasHeightForWidth())
        self.cell50.setSizePolicy(sizePolicy)
        self.cell50.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell50.setFont(font)
        self.cell50.setMaxLength(1)
        self.cell50.setAlignment(QtCore.Qt.AlignCenter)
        self.cell50.setObjectName(_fromUtf8("cell50"))
        self.gridLayout_3.addWidget(self.cell50, 6, 5, 1, 1)
        self.line_2 = QtGui.QFrame(self.centralwidget)
        self.line_2.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout_3.addWidget(self.line_2, 3, 0, 1, 11)
        self.cell11 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell11.sizePolicy().hasHeightForWidth())
        self.cell11.setSizePolicy(sizePolicy)
        self.cell11.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell11.setFont(font)
        self.cell11.setMaxLength(1)
        self.cell11.setAlignment(QtCore.Qt.AlignCenter)
        self.cell11.setObjectName(_fromUtf8("cell11"))
        self.gridLayout_3.addWidget(self.cell11, 1, 1, 1, 1)
        self.cell43 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell43.sizePolicy().hasHeightForWidth())
        self.cell43.setSizePolicy(sizePolicy)
        self.cell43.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell43.setFont(font)
        self.cell43.setMaxLength(1)
        self.cell43.setAlignment(QtCore.Qt.AlignCenter)
        self.cell43.setObjectName(_fromUtf8("cell43"))
        self.gridLayout_3.addWidget(self.cell43, 5, 8, 1, 1)
        self.cell65 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell65.sizePolicy().hasHeightForWidth())
        self.cell65.setSizePolicy(sizePolicy)
        self.cell65.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell65.setFont(font)
        self.cell65.setMaxLength(1)
        self.cell65.setAlignment(QtCore.Qt.AlignCenter)
        self.cell65.setObjectName(_fromUtf8("cell65"))
        self.gridLayout_3.addWidget(self.cell65, 9, 1, 1, 1)
        self.cell5 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell5.sizePolicy().hasHeightForWidth())
        self.cell5.setSizePolicy(sizePolicy)
        self.cell5.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell5.setFont(font)
        self.cell5.setMaxLength(1)
        self.cell5.setAlignment(QtCore.Qt.AlignCenter)
        self.cell5.setObjectName(_fromUtf8("cell5"))
        self.gridLayout_3.addWidget(self.cell5, 0, 5, 1, 1)
        self.cell25 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell25.sizePolicy().hasHeightForWidth())
        self.cell25.setSizePolicy(sizePolicy)
        self.cell25.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell25.setFont(font)
        self.cell25.setMaxLength(1)
        self.cell25.setAlignment(QtCore.Qt.AlignCenter)
        self.cell25.setObjectName(_fromUtf8("cell25"))
        self.gridLayout_3.addWidget(self.cell25, 2, 8, 1, 1)
        self.cell19 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell19.sizePolicy().hasHeightForWidth())
        self.cell19.setSizePolicy(sizePolicy)
        self.cell19.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell19.setFont(font)
        self.cell19.setMaxLength(1)
        self.cell19.setAlignment(QtCore.Qt.AlignCenter)
        self.cell19.setObjectName(_fromUtf8("cell19"))
        self.gridLayout_3.addWidget(self.cell19, 2, 0, 1, 1)
        self.cell14 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell14.sizePolicy().hasHeightForWidth())
        self.cell14.setSizePolicy(sizePolicy)
        self.cell14.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell14.setFont(font)
        self.cell14.setMaxLength(1)
        self.cell14.setAlignment(QtCore.Qt.AlignCenter)
        self.cell14.setObjectName(_fromUtf8("cell14"))
        self.gridLayout_3.addWidget(self.cell14, 1, 5, 1, 1)
        self.cell2 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell2.sizePolicy().hasHeightForWidth())
        self.cell2.setSizePolicy(sizePolicy)
        self.cell2.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell2.setFont(font)
        self.cell2.setMaxLength(1)
        self.cell2.setAlignment(QtCore.Qt.AlignCenter)
        self.cell2.setObjectName(_fromUtf8("cell2"))
        self.gridLayout_3.addWidget(self.cell2, 0, 1, 1, 1)
        self.cell56 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell56.sizePolicy().hasHeightForWidth())
        self.cell56.setSizePolicy(sizePolicy)
        self.cell56.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell56.setFont(font)
        self.cell56.setMaxLength(1)
        self.cell56.setAlignment(QtCore.Qt.AlignCenter)
        self.cell56.setObjectName(_fromUtf8("cell56"))
        self.gridLayout_3.addWidget(self.cell56, 8, 1, 1, 1)
        self.cell4 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell4.sizePolicy().hasHeightForWidth())
        self.cell4.setSizePolicy(sizePolicy)
        self.cell4.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell4.setFont(font)
        self.cell4.setMaxLength(1)
        self.cell4.setAlignment(QtCore.Qt.AlignCenter)
        self.cell4.setObjectName(_fromUtf8("cell4"))
        self.gridLayout_3.addWidget(self.cell4, 0, 4, 1, 1)
        self.cell6 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell6.sizePolicy().hasHeightForWidth())
        self.cell6.setSizePolicy(sizePolicy)
        self.cell6.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell6.setFont(font)
        self.cell6.setMaxLength(1)
        self.cell6.setAlignment(QtCore.Qt.AlignCenter)
        self.cell6.setObjectName(_fromUtf8("cell6"))
        self.gridLayout_3.addWidget(self.cell6, 0, 6, 1, 1)
        self.line_6 = QtGui.QFrame(self.centralwidget)
        self.line_6.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.line_6.setFont(font)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.gridLayout_3.addWidget(self.line_6, 8, 7, 2, 1)
        self.cell10 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell10.sizePolicy().hasHeightForWidth())
        self.cell10.setSizePolicy(sizePolicy)
        self.cell10.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell10.setFont(font)
        self.cell10.setMaxLength(1)
        self.cell10.setAlignment(QtCore.Qt.AlignCenter)
        self.cell10.setObjectName(_fromUtf8("cell10"))
        self.gridLayout_3.addWidget(self.cell10, 1, 0, 1, 1)
        self.cell12 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell12.sizePolicy().hasHeightForWidth())
        self.cell12.setSizePolicy(sizePolicy)
        self.cell12.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell12.setFont(font)
        self.cell12.setMaxLength(1)
        self.cell12.setAlignment(QtCore.Qt.AlignCenter)
        self.cell12.setObjectName(_fromUtf8("cell12"))
        self.gridLayout_3.addWidget(self.cell12, 1, 2, 1, 1)
        self.cell34 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell34.sizePolicy().hasHeightForWidth())
        self.cell34.setSizePolicy(sizePolicy)
        self.cell34.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell34.setFont(font)
        self.cell34.setMaxLength(1)
        self.cell34.setAlignment(QtCore.Qt.AlignCenter)
        self.cell34.setObjectName(_fromUtf8("cell34"))
        self.gridLayout_3.addWidget(self.cell34, 4, 8, 1, 1)
        self.cell3 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell3.sizePolicy().hasHeightForWidth())
        self.cell3.setSizePolicy(sizePolicy)
        self.cell3.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell3.setFont(font)
        self.cell3.setMaxLength(1)
        self.cell3.setAlignment(QtCore.Qt.AlignCenter)
        self.cell3.setObjectName(_fromUtf8("cell3"))
        self.gridLayout_3.addWidget(self.cell3, 0, 2, 1, 1)
        self.cell53 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell53.sizePolicy().hasHeightForWidth())
        self.cell53.setSizePolicy(sizePolicy)
        self.cell53.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell53.setFont(font)
        self.cell53.setMaxLength(1)
        self.cell53.setAlignment(QtCore.Qt.AlignCenter)
        self.cell53.setObjectName(_fromUtf8("cell53"))
        self.gridLayout_3.addWidget(self.cell53, 6, 9, 1, 1)
        self.cell21 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell21.sizePolicy().hasHeightForWidth())
        self.cell21.setSizePolicy(sizePolicy)
        self.cell21.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell21.setFont(font)
        self.cell21.setMaxLength(1)
        self.cell21.setAlignment(QtCore.Qt.AlignCenter)
        self.cell21.setObjectName(_fromUtf8("cell21"))
        self.gridLayout_3.addWidget(self.cell21, 2, 2, 1, 1)
        self.cell35 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell35.sizePolicy().hasHeightForWidth())
        self.cell35.setSizePolicy(sizePolicy)
        self.cell35.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell35.setFont(font)
        self.cell35.setMaxLength(1)
        self.cell35.setAlignment(QtCore.Qt.AlignCenter)
        self.cell35.setObjectName(_fromUtf8("cell35"))
        self.gridLayout_3.addWidget(self.cell35, 4, 9, 1, 1)
        self.cell29 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell29.sizePolicy().hasHeightForWidth())
        self.cell29.setSizePolicy(sizePolicy)
        self.cell29.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell29.setFont(font)
        self.cell29.setMaxLength(1)
        self.cell29.setAlignment(QtCore.Qt.AlignCenter)
        self.cell29.setObjectName(_fromUtf8("cell29"))
        self.gridLayout_3.addWidget(self.cell29, 4, 1, 1, 1)
        self.cell27 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell27.sizePolicy().hasHeightForWidth())
        self.cell27.setSizePolicy(sizePolicy)
        self.cell27.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell27.setFont(font)
        self.cell27.setMaxLength(1)
        self.cell27.setAlignment(QtCore.Qt.AlignCenter)
        self.cell27.setObjectName(_fromUtf8("cell27"))
        self.gridLayout_3.addWidget(self.cell27, 2, 10, 1, 1)
        self.cell18 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell18.sizePolicy().hasHeightForWidth())
        self.cell18.setSizePolicy(sizePolicy)
        self.cell18.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell18.setFont(font)
        self.cell18.setMaxLength(1)
        self.cell18.setAlignment(QtCore.Qt.AlignCenter)
        self.cell18.setObjectName(_fromUtf8("cell18"))
        self.gridLayout_3.addWidget(self.cell18, 1, 10, 1, 1)
        self.line_5 = QtGui.QFrame(self.centralwidget)
        self.line_5.setMinimumSize(QtCore.QSize(10, 0))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.line_5.setFont(font)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.gridLayout_3.addWidget(self.line_5, 8, 3, 2, 1)
        self.cell80 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell80.sizePolicy().hasHeightForWidth())
        self.cell80.setSizePolicy(sizePolicy)
        self.cell80.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell80.setFont(font)
        self.cell80.setMaxLength(1)
        self.cell80.setAlignment(QtCore.Qt.AlignCenter)
        self.cell80.setObjectName(_fromUtf8("cell80"))
        self.gridLayout_3.addWidget(self.cell80, 10, 9, 1, 1)
        self.cell37 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell37.sizePolicy().hasHeightForWidth())
        self.cell37.setSizePolicy(sizePolicy)
        self.cell37.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell37.setFont(font)
        self.cell37.setMaxLength(1)
        self.cell37.setAlignment(QtCore.Qt.AlignCenter)
        self.cell37.setObjectName(_fromUtf8("cell37"))
        self.gridLayout_3.addWidget(self.cell37, 5, 0, 1, 1)
        self.cell36 = QtGui.QLineEdit(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cell36.sizePolicy().hasHeightForWidth())
        self.cell36.setSizePolicy(sizePolicy)
        self.cell36.setMinimumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.cell36.setFont(font)
        self.cell36.setMaxLength(1)
        self.cell36.setAlignment(QtCore.Qt.AlignCenter)
        self.cell36.setObjectName(_fromUtf8("cell36"))
        self.gridLayout_3.addWidget(self.cell36, 4, 10, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 0, 0, 20)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_2 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.cell1, self.cell2)
        MainWindow.setTabOrder(self.cell2, self.cell3)
        MainWindow.setTabOrder(self.cell3, self.cell10)
        MainWindow.setTabOrder(self.cell10, self.cell11)
        MainWindow.setTabOrder(self.cell11, self.cell12)
        MainWindow.setTabOrder(self.cell12, self.cell19)
        MainWindow.setTabOrder(self.cell19, self.cell20)
        MainWindow.setTabOrder(self.cell20, self.cell21)
        MainWindow.setTabOrder(self.cell21, self.cell4)
        MainWindow.setTabOrder(self.cell4, self.cell5)
        MainWindow.setTabOrder(self.cell5, self.cell6)
        MainWindow.setTabOrder(self.cell6, self.cell13)
        MainWindow.setTabOrder(self.cell13, self.cell14)
        MainWindow.setTabOrder(self.cell14, self.cell15)
        MainWindow.setTabOrder(self.cell15, self.cell22)
        MainWindow.setTabOrder(self.cell22, self.cell23)
        MainWindow.setTabOrder(self.cell23, self.cell24)
        MainWindow.setTabOrder(self.cell24, self.cell7)
        MainWindow.setTabOrder(self.cell7, self.cell8)
        MainWindow.setTabOrder(self.cell8, self.cell9)
        MainWindow.setTabOrder(self.cell9, self.cell16)
        MainWindow.setTabOrder(self.cell16, self.cell17)
        MainWindow.setTabOrder(self.cell17, self.cell18)
        MainWindow.setTabOrder(self.cell18, self.cell25)
        MainWindow.setTabOrder(self.cell25, self.cell26)
        MainWindow.setTabOrder(self.cell26, self.cell27)
        MainWindow.setTabOrder(self.cell27, self.cell28)
        MainWindow.setTabOrder(self.cell28, self.cell29)
        MainWindow.setTabOrder(self.cell29, self.cell30)
        MainWindow.setTabOrder(self.cell30, self.cell37)
        MainWindow.setTabOrder(self.cell37, self.cell38)
        MainWindow.setTabOrder(self.cell38, self.cell39)
        MainWindow.setTabOrder(self.cell39, self.cell46)
        MainWindow.setTabOrder(self.cell46, self.cell47)
        MainWindow.setTabOrder(self.cell47, self.cell48)
        MainWindow.setTabOrder(self.cell48, self.cell31)
        MainWindow.setTabOrder(self.cell31, self.cell32)
        MainWindow.setTabOrder(self.cell32, self.cell33)
        MainWindow.setTabOrder(self.cell33, self.cell40)
        MainWindow.setTabOrder(self.cell40, self.cell41)
        MainWindow.setTabOrder(self.cell41, self.cell42)
        MainWindow.setTabOrder(self.cell42, self.cell49)
        MainWindow.setTabOrder(self.cell49, self.cell50)
        MainWindow.setTabOrder(self.cell50, self.cell51)
        MainWindow.setTabOrder(self.cell51, self.cell34)
        MainWindow.setTabOrder(self.cell34, self.cell35)
        MainWindow.setTabOrder(self.cell35, self.cell36)
        MainWindow.setTabOrder(self.cell36, self.cell43)
        MainWindow.setTabOrder(self.cell43, self.cell44)
        MainWindow.setTabOrder(self.cell44, self.cell45)
        MainWindow.setTabOrder(self.cell45, self.cell52)
        MainWindow.setTabOrder(self.cell52, self.cell53)
        MainWindow.setTabOrder(self.cell53, self.cell54)
        MainWindow.setTabOrder(self.cell54, self.cell55)
        MainWindow.setTabOrder(self.cell55, self.cell56)
        MainWindow.setTabOrder(self.cell56, self.cell57)
        MainWindow.setTabOrder(self.cell57, self.cell64)
        MainWindow.setTabOrder(self.cell64, self.cell65)
        MainWindow.setTabOrder(self.cell65, self.cell66)
        MainWindow.setTabOrder(self.cell66, self.cell73)
        MainWindow.setTabOrder(self.cell73, self.cell74)
        MainWindow.setTabOrder(self.cell74, self.cell75)
        MainWindow.setTabOrder(self.cell75, self.cell58)
        MainWindow.setTabOrder(self.cell58, self.cell59)
        MainWindow.setTabOrder(self.cell59, self.cell60)
        MainWindow.setTabOrder(self.cell60, self.cell67)
        MainWindow.setTabOrder(self.cell67, self.cell68)
        MainWindow.setTabOrder(self.cell68, self.cell69)
        MainWindow.setTabOrder(self.cell69, self.cell76)
        MainWindow.setTabOrder(self.cell76, self.cell77)
        MainWindow.setTabOrder(self.cell77, self.cell78)
        MainWindow.setTabOrder(self.cell78, self.cell61)
        MainWindow.setTabOrder(self.cell61, self.cell62)
        MainWindow.setTabOrder(self.cell62, self.cell63)
        MainWindow.setTabOrder(self.cell63, self.cell70)
        MainWindow.setTabOrder(self.cell70, self.cell71)
        MainWindow.setTabOrder(self.cell71, self.cell72)
        MainWindow.setTabOrder(self.cell72, self.cell79)
        MainWindow.setTabOrder(self.cell79, self.cell80)
        MainWindow.setTabOrder(self.cell80, self.cell81)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Sudoku solver", None))
        self.label.setText(_translate("MainWindow", "Sudoku Solver", None))
        self.pushButton.setText(_translate("MainWindow", "Reset", None))
        self.pushButton_2.setText(_translate("MainWindow", "Solve", None))

